SCHEMA = {
    "id": "TEXT PRIMARY KEY",
    "name": "varchar(70)",
    "description": "text",
    "tagline": "text",
    "producturl": "varchar(500)",
    "imageurl": "varchar(500)",
    "ratingtext": "varchar(10)",
    "ratingvalue": "varchar(10)",
    "averagerating": "varchar(10)",
    "totalratings": "varchar(10)",
    "discountedPrice": "varchar(10)",
    "discountPercentage": "varchar(10)",
    "originalPrice": "varchar(10)",
    "city": "varchar(30)",
    "country": "varchar(30)",
    "countryflagurl": "varchar(500)",
    "userRating": "JSONB",
}
